heartbeat.monitors:

- type: http
  urls: ["https://{{ domain }}"]
  schedule: "@every 10s"
  timeout: 3s
  check.response.status: 200

- type: http
  urls: ["https://kibana.{{ domain }}"]
  schedule: "@every 10s"
  timeout: 3s
  check.response.status: 200

- type: http
  urls: ["{{ elasticsearch_host }}"]
  username: {{ elasticsearch_user }}
  password: "${ES_PWD}"
  schedule: "@every 10s"
  timeout: 3s
  check.response.status: 200


name: "{{ inventory_hostname }}"
tags: ["{{ env }}"]


processors:
- add_cloud_metadata: ~
- add_host_metadata: ~
- add_observer_metadata:
    geo:
      name: europe


xpack.monitoring.enabled: true


output.elasticsearch:
  hosts: ["{{ elasticsearch_host }}"]
  username: "{{ elasticsearch_user }}"
  password: "${ES_PWD}"


# No dashboards to import as of 7.0
